import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          inter.className,
          "prose min-h-screen px-4 py-2 bg-blue-100/30"
        )}
      >
        <div className="flex gap-8 min-h-full">
          <Sidebar className="" />
          <div className="min-w-full py-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
